spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu_room
    username: root
    password: asdfg567
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

