server:
  port: 5000

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu_room
    username: root
    password: asdfg567
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
    show-sql: true

jwt:
  auth:
    app: EduRoom-App
    secret_key: asdfg567
    expires_in: 3600

